volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - foodgram_network

  backend:
    image: nataliakosh17/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - foodgram_network

  frontend:
    image: nataliakosh17/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/* /frontend_static/
    volumes:
      - static_volume:/frontend_static
    networks:
      - foodgram_network

  gateway:
    image: nataliakosh17/foodgram_gateway:latest
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/app/media
      - ./docs:/usr/share/nginx/html/api/docs
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network

networks:
  foodgram_network:
    driver: bridge
